### ISSUE TITLE
Machinist Battery Gauge Bug

### ISSUE THREAD

**Issue by bananafishbone-s** [Necroskillz/ffxiv-rotation-dojo#3]
When using Automaton Queen on MCH, it should consume all battery in the gauge with a _minimum_ cost of 50 gauge. As it is now, the Automaton Queen skill simply consumes a flat 50 gauge. 

Sequence of actions that lead to the problem:
1. Build Battery Gauge to any value above 50
2. Use Automaton Queen
3. You will notice that 50 gauge is subtracted from the meter, as opposed to setting gauge to 0.

**Comment by Necroskillz** [comment]
I somehow missed a notification about this issue, but i also noticed it and its already fixed.
